server:
  ip: "54.36.191.29"
  port: 25
  ssl_port: 465
  tls_port: 587
domain_check:
  sensitive: 5
blacklist:
  api_key: "AzKegv6KxuwTqWJNl9Iahgk0eul6iw14"
shorten:
  api_key: "64tNM9WaiGe6EX23cGSI6ZDfqRtqPgJlF866CAcW"
ssl:
  certificate_path: "/home/debian/java/crtf/ubmail.jks"
  pass: "ubmail"
mail:
  username: "postmaster@darkhorizon.es"
  password: "password"
mysql:
  host: "54.36.191.29"
  port: 3306
  username: "root"
  password: "password"
  database: "ubmail"
