server:
  ip: "localhost"
  remote: "54.36.191.29"
  port: 25
  ssl_port: 465
domain_check:
  sensitive: 5
  domains:
    - "ub.edu"
    - "campusvirtual.ub.edu"
    - "www.ub.edu"
blacklist:
  api_key: "7jL0GedmCBjSBNro5Vcjxy3Udffdg660"