server:
  ip: "localhost"
  local: "127.0.0.1"
  remote: "54.36.191.29"
  port: 25
  ssl_port: 465
  tls_port: 587
domain_check:
  sensitive: 5
blacklist:
  api_key: "AzKegv6KxuwTqWJNl9Iahgk0eul6iw14"
shorten:
  api_key: "64tNM9WaiGe6EX23cGSI6ZDfqRtqPgJlF866CAcW"
ssl:
  local: "C:\\Users\\DarkDhz\\IdeaProjects\\Ubmail\\crtf\\ubmail.jks"
  remote: "/home/debian/java/crtf"
  certificate_path: "C:\\Users\\DarkDhz\\IdeaProjects\\Ubmail\\crtf\\ubmail.jks"
  pass: "ubmail"