server:
  ip: "localhost"
  remote: "54.36.191.29"
  port: 25
  ssl_port: 465
domain_check:
  sensitive: 5
  domains:
    - "ub.edu"
    - "campusvirtual.ub.edu"
    - "www.ub.edu"
banned_domains:
  domains:
    - 'upc.edu'
    - 'www.upc.edu'
    - 'uab.edu'
blacklist:
  api_key: "AzKegv6KxuwTqWJNl9Iahgk0eul6iw14"
ssl:
  local: "C:\\Users\\DarkDhz\\IdeaProjects\\Ubmail\\crtf\\ubmail.jks"
  remote: "/home/debian/java/crtf"
  certificate_path: "C:\\Users\\DarkDhz\\IdeaProjects\\Ubmail\\crtf\\ubmail.jks"
  pass: "ubmail"